project_id = "urpekpxpvoaqagdjyerm"

[functions.groq-proxy]
verify_jwt = false

[functions.send-confirmation]
verify_jwt = false

[functions.embed-query]
verify_jwt = false

[functions.train-knowledge]
verify_jwt = true

[functions.contact-submit]
verify_jwt = false
