project_id = "urpekpxpvoaqagdjyerm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = false

[realtime]
enabled = true
ip_version = "dual"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
jwt_expiry = 3600
refresh_token_rotation_enabled = true
external_email_enabled = true
external_phone_enabled = true
sms_test_otp = "123456"
email_test_otp = "123456"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge-runtime]
enabled = true
port = 54330
inspector_port = 54331

[functions.groq-proxy]
verify_jwt = false

[functions.send-confirmation]
verify_jwt = false

[functions.embed-query]
verify_jwt = false

[functions.train-knowledge]
verify_jwt = true

[functions.contact-submit]
verify_jwt = false

[functions.verify-passcode]
verify_jwt = false
