// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urpekpxpvoaqagdjyerm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVycGVrcHhwdm9hcWFnZGp5ZXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDQxMTUsImV4cCI6MjA3MDU4MDExNX0.3STx94LCn8utO9DzqOsRlZ1Iesrdd4DSfbykeBSmfco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});